[package]
name = "jarecki"
version = "0.1.0"
edition = "2024"

[dependencies]
curve25519-dalek = "4.1.3"
itertools = "0.14.0"
rand = "0.8"
sha2 = "0.10.9"
shamirsecretsharing = "0.1.7"
thiserror = "2.0.17"
voprf = "0.5.0"
